export const AUTHENTICATING = 'AUTHENTICATING';
export const AUTHENTICATION_FAILED = 'AUTHENTICATION_FAILED';
export const AUTHENTICATED = 'AUTHENTICATED';

export const REGISTER = 'REGISTER';
export const REGISTRATION_FAILED = 'REGISTRATION_FAILED';
export const REGISTERING = 'REGISTERING';
