export const REGISTER_SUCCESS = 'REGISTER';
export const REGISTRATION_FAILED = 'REGISTRATION_FAILED';
export const REGISTERING = 'REGISTERING';
export const LOAD_USER = 'LOAD_USER';
export const AUTHENTICATING = 'AUTHENTICATING';
export const AUTHENTICATION_FAILED = 'AUTHENTICATION_FAILED';
export const AUTHENTICATED = 'AUTHENTICATED';

export const LOADING_DATA = 'LOADING_DATA';
export const GET_JOKES = 'GET_JOKES';
export const GET_ANIME = 'GET_ANIME';
